# coding: utf-8

"""
    Wishlist Service

    API for managing wishlists

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from wishlist.models.wishlist_merge_wishlists_request import WishlistMergeWishlistsRequest

class TestWishlistMergeWishlistsRequest(unittest.TestCase):
    """WishlistMergeWishlistsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WishlistMergeWishlistsRequest:
        """Test WishlistMergeWishlistsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WishlistMergeWishlistsRequest`
        """
        model = WishlistMergeWishlistsRequest()
        if include_optional:
            return WishlistMergeWishlistsRequest(
                tenant_id = '',
                starting_wishlist_id = '',
                customer_grn = '',
                target_wishlist_id = ''
            )
        else:
            return WishlistMergeWishlistsRequest(
                tenant_id = '',
                starting_wishlist_id = '',
                customer_grn = '',
        )
        """

    def testWishlistMergeWishlistsRequest(self):
        """Test WishlistMergeWishlistsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
