# coding: utf-8

"""
    Wishlist Service

    API for managing wishlists

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from wishlist.models.wishlist_add_item_to_wishlist_request import WishlistAddItemToWishlistRequest

class TestWishlistAddItemToWishlistRequest(unittest.TestCase):
    """WishlistAddItemToWishlistRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WishlistAddItemToWishlistRequest:
        """Test WishlistAddItemToWishlistRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WishlistAddItemToWishlistRequest`
        """
        model = WishlistAddItemToWishlistRequest()
        if include_optional:
            return WishlistAddItemToWishlistRequest(
                tenant_id = '',
                wishlist_id = '',
                item_grn = '',
                preferred_quantity = '',
                description = wishlist.models.wishlist_localized_text.wishlistLocalizedText(
                    value = {
                        'key' : ''
                        }, ),
                customer_grn = ''
            )
        else:
            return WishlistAddItemToWishlistRequest(
                tenant_id = '',
                wishlist_id = '',
                item_grn = '',
        )
        """

    def testWishlistAddItemToWishlistRequest(self):
        """Test WishlistAddItemToWishlistRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
