# coding: utf-8

"""
    Wishlist Service

    API for managing wishlists

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from wishlist.models.wishlist_create_wishlist_request import WishlistCreateWishlistRequest

class TestWishlistCreateWishlistRequest(unittest.TestCase):
    """WishlistCreateWishlistRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WishlistCreateWishlistRequest:
        """Test WishlistCreateWishlistRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WishlistCreateWishlistRequest`
        """
        model = WishlistCreateWishlistRequest()
        if include_optional:
            return WishlistCreateWishlistRequest(
                tenant_id = '',
                privacy = 'PRIVACY_UNKNOWN',
                label = wishlist.models.wishlist_localized_text.wishlistLocalizedText(
                    value = {
                        'key' : ''
                        }, ),
                description = wishlist.models.wishlist_localized_text.wishlistLocalizedText(
                    value = {
                        'key' : ''
                        }, ),
                customer_grn = '',
                is_default = True
            )
        else:
            return WishlistCreateWishlistRequest(
                tenant_id = '',
                privacy = 'PRIVACY_UNKNOWN',
        )
        """

    def testWishlistCreateWishlistRequest(self):
        """Test WishlistCreateWishlistRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
