# coding: utf-8

"""
    Wishlist Service

    API for managing wishlists

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from wishlist.models.wishlist_list_wishlists_response import WishlistListWishlistsResponse

class TestWishlistListWishlistsResponse(unittest.TestCase):
    """WishlistListWishlistsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WishlistListWishlistsResponse:
        """Test WishlistListWishlistsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WishlistListWishlistsResponse`
        """
        model = WishlistListWishlistsResponse()
        if include_optional:
            return WishlistListWishlistsResponse(
                wishlist = [
                    wishlist.models.wishlist_wishlist_response.wishlistWishlistResponse(
                        id = '', 
                        grn = '', 
                        shared_code = '', 
                        privacy = 'PRIVACY_UNKNOWN', 
                        label = wishlist.models.wishlist_localized_text.wishlistLocalizedText(
                            value = {
                                'key' : ''
                                }, ), 
                        description = wishlist.models.wishlist_localized_text.wishlistLocalizedText(), 
                        customer_grn = '', 
                        is_default = True, 
                        items_count = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                next_page_token = ''
            )
        else:
            return WishlistListWishlistsResponse(
        )
        """

    def testWishlistListWishlistsResponse(self):
        """Test WishlistListWishlistsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
