# coding: utf-8

"""
    Wishlist Service

    API for managing wishlists

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wishlist.api.wishlist_api import WishlistApi


class TestWishlistApi(unittest.TestCase):
    """WishlistApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WishlistApi()

    def tearDown(self) -> None:
        pass

    def test_wishlist_add_item_to_wishlist(self) -> None:
        """Test case for wishlist_add_item_to_wishlist

        """
        pass

    def test_wishlist_are_items_in_wishlists(self) -> None:
        """Test case for wishlist_are_items_in_wishlists

        """
        pass

    def test_wishlist_bulk_create_sharing(self) -> None:
        """Test case for wishlist_bulk_create_sharing

        Sharing endpoints
        """
        pass

    def test_wishlist_bulk_remove_items_from_wishlists(self) -> None:
        """Test case for wishlist_bulk_remove_items_from_wishlists

        BulkRemoveItemsFromWishlists removes items from wishlists.
        """
        pass

    def test_wishlist_bulk_revoke_sharing(self) -> None:
        """Test case for wishlist_bulk_revoke_sharing

        """
        pass

    def test_wishlist_create_wishlist(self) -> None:
        """Test case for wishlist_create_wishlist

        """
        pass

    def test_wishlist_delete_wishlist(self) -> None:
        """Test case for wishlist_delete_wishlist

        """
        pass

    def test_wishlist_get_item_from_wishlist(self) -> None:
        """Test case for wishlist_get_item_from_wishlist

        """
        pass

    def test_wishlist_get_wishlist_by_id(self) -> None:
        """Test case for wishlist_get_wishlist_by_id

        """
        pass

    def test_wishlist_get_wishlist_by_shared_code(self) -> None:
        """Test case for wishlist_get_wishlist_by_shared_code

        """
        pass

    def test_wishlist_list_wishlist_items(self) -> None:
        """Test case for wishlist_list_wishlist_items

        """
        pass

    def test_wishlist_list_wishlists(self) -> None:
        """Test case for wishlist_list_wishlists

        """
        pass

    def test_wishlist_merge_wishlists(self) -> None:
        """Test case for wishlist_merge_wishlists

        """
        pass

    def test_wishlist_remove_item_from_wishlist(self) -> None:
        """Test case for wishlist_remove_item_from_wishlist

        """
        pass

    def test_wishlist_update_item_in_wishlist(self) -> None:
        """Test case for wishlist_update_item_in_wishlist

        """
        pass

    def test_wishlist_update_wishlist(self) -> None:
        """Test case for wishlist_update_wishlist

        """
        pass


if __name__ == '__main__':
    unittest.main()
