# coding: utf-8

"""
    Wishlist Service

    API for managing wishlists

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from wishlist.models.wishlist_are_items_in_wishlists_response_payload import WishlistAreItemsInWishlistsResponsePayload

class TestWishlistAreItemsInWishlistsResponsePayload(unittest.TestCase):
    """WishlistAreItemsInWishlistsResponsePayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WishlistAreItemsInWishlistsResponsePayload:
        """Test WishlistAreItemsInWishlistsResponsePayload
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WishlistAreItemsInWishlistsResponsePayload`
        """
        model = WishlistAreItemsInWishlistsResponsePayload()
        if include_optional:
            return WishlistAreItemsInWishlistsResponsePayload(
                wishlist_grn_to_wishlist_item_grn_map = {
                    'key' : ''
                    }
            )
        else:
            return WishlistAreItemsInWishlistsResponsePayload(
        )
        """

    def testWishlistAreItemsInWishlistsResponsePayload(self):
        """Test WishlistAreItemsInWishlistsResponsePayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
