# coding: utf-8

"""
    Wishlist Service

    API for managing wishlists

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from wishlist.models.wishlist_get_wishlist_by_shared_code_request import WishlistGetWishlistBySharedCodeRequest

class TestWishlistGetWishlistBySharedCodeRequest(unittest.TestCase):
    """WishlistGetWishlistBySharedCodeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WishlistGetWishlistBySharedCodeRequest:
        """Test WishlistGetWishlistBySharedCodeRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WishlistGetWishlistBySharedCodeRequest`
        """
        model = WishlistGetWishlistBySharedCodeRequest()
        if include_optional:
            return WishlistGetWishlistBySharedCodeRequest(
                tenant_id = '',
                shared_code = '',
                customer_grn = ''
            )
        else:
            return WishlistGetWishlistBySharedCodeRequest(
                tenant_id = '',
                shared_code = '',
        )
        """

    def testWishlistGetWishlistBySharedCodeRequest(self):
        """Test WishlistGetWishlistBySharedCodeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
