# coding: utf-8

"""
    Wishlist Service

    API for managing wishlists

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from wishlist.models.wishlist_list_wishlist_items_request import WishlistListWishlistItemsRequest

class TestWishlistListWishlistItemsRequest(unittest.TestCase):
    """WishlistListWishlistItemsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WishlistListWishlistItemsRequest:
        """Test WishlistListWishlistItemsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WishlistListWishlistItemsRequest`
        """
        model = WishlistListWishlistItemsRequest()
        if include_optional:
            return WishlistListWishlistItemsRequest(
                tenant_id = '',
                wishlist_id = '',
                customer_grn = '',
                page_size = 56,
                page_token = ''
            )
        else:
            return WishlistListWishlistItemsRequest(
                tenant_id = '',
                wishlist_id = '',
        )
        """

    def testWishlistListWishlistItemsRequest(self):
        """Test WishlistListWishlistItemsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
