# coding: utf-8

"""
    Wishlist Service

    API for managing wishlists

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from wishlist.models.wishlist_remove_item_from_wishlist_request import WishlistRemoveItemFromWishlistRequest

class TestWishlistRemoveItemFromWishlistRequest(unittest.TestCase):
    """WishlistRemoveItemFromWishlistRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WishlistRemoveItemFromWishlistRequest:
        """Test WishlistRemoveItemFromWishlistRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WishlistRemoveItemFromWishlistRequest`
        """
        model = WishlistRemoveItemFromWishlistRequest()
        if include_optional:
            return WishlistRemoveItemFromWishlistRequest(
                tenant_id = '',
                id = ''
            )
        else:
            return WishlistRemoveItemFromWishlistRequest(
                tenant_id = '',
                id = '',
        )
        """

    def testWishlistRemoveItemFromWishlistRequest(self):
        """Test WishlistRemoveItemFromWishlistRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
