# coding: utf-8

"""
    Wishlist Service

    API for managing wishlists

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from wishlist.models.wishlist_delete_wishlist_request import WishlistDeleteWishlistRequest

class TestWishlistDeleteWishlistRequest(unittest.TestCase):
    """WishlistDeleteWishlistRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WishlistDeleteWishlistRequest:
        """Test WishlistDeleteWishlistRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WishlistDeleteWishlistRequest`
        """
        model = WishlistDeleteWishlistRequest()
        if include_optional:
            return WishlistDeleteWishlistRequest(
                tenant_id = '',
                id = ''
            )
        else:
            return WishlistDeleteWishlistRequest(
                tenant_id = '',
                id = '',
        )
        """

    def testWishlistDeleteWishlistRequest(self):
        """Test WishlistDeleteWishlistRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
