# coding: utf-8

"""
    Wishlist Service

    API for managing wishlists

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from wishlist.models.wishlist_are_items_in_wishlists_response import WishlistAreItemsInWishlistsResponse

class TestWishlistAreItemsInWishlistsResponse(unittest.TestCase):
    """WishlistAreItemsInWishlistsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WishlistAreItemsInWishlistsResponse:
        """Test WishlistAreItemsInWishlistsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WishlistAreItemsInWishlistsResponse`
        """
        model = WishlistAreItemsInWishlistsResponse()
        if include_optional:
            return WishlistAreItemsInWishlistsResponse(
                item_grn_map = {
                    'key' : wishlist.models.wishlist_are_items_in_wishlists_response_payload.wishlistAreItemsInWishlistsResponsePayload(
                        wishlist_grn_to_wishlist_item_grn_map = {
                            'key' : ''
                            }, )
                    }
            )
        else:
            return WishlistAreItemsInWishlistsResponse(
        )
        """

    def testWishlistAreItemsInWishlistsResponse(self):
        """Test WishlistAreItemsInWishlistsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
