# coding: utf-8

"""
    Wishlist Service

    API for managing wishlists

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from wishlist.models.wishlist_permission import WishlistPermission

class TestWishlistPermission(unittest.TestCase):
    """WishlistPermission unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWishlistPermission(self):
        """Test WishlistPermission"""
        # inst = WishlistPermission()

if __name__ == '__main__':
    unittest.main()
