# coding: utf-8

"""
    Wishlist Service

    API for managing wishlists

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from wishlist.models.wishlist_list_wishlist_items_response import WishlistListWishlistItemsResponse

class TestWishlistListWishlistItemsResponse(unittest.TestCase):
    """WishlistListWishlistItemsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WishlistListWishlistItemsResponse:
        """Test WishlistListWishlistItemsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WishlistListWishlistItemsResponse`
        """
        model = WishlistListWishlistItemsResponse()
        if include_optional:
            return WishlistListWishlistItemsResponse(
                wishlist_items = [
                    wishlist.models.wishlist_wishlist_item_response.wishlistWishlistItemResponse(
                        id = '', 
                        grn = '', 
                        wishlist_id = '', 
                        item_grn = '', 
                        preferred_quantity = '', 
                        description = wishlist.models.wishlist_localized_text.wishlistLocalizedText(
                            value = {
                                'key' : ''
                                }, ), 
                        added_by_customer_grn = '', 
                        added_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                next_page_token = ''
            )
        else:
            return WishlistListWishlistItemsResponse(
        )
        """

    def testWishlistListWishlistItemsResponse(self):
        """Test WishlistListWishlistItemsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
