# coding: utf-8

"""
    Wishlist Service

    API for managing wishlists

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from wishlist.models.wishlist_update_item_in_wishlist_request import WishlistUpdateItemInWishlistRequest

class TestWishlistUpdateItemInWishlistRequest(unittest.TestCase):
    """WishlistUpdateItemInWishlistRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WishlistUpdateItemInWishlistRequest:
        """Test WishlistUpdateItemInWishlistRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WishlistUpdateItemInWishlistRequest`
        """
        model = WishlistUpdateItemInWishlistRequest()
        if include_optional:
            return WishlistUpdateItemInWishlistRequest(
                tenant_id = '',
                id = '',
                payload = wishlist.models.wishlist_update_item_in_wishlist_request_payload.wishlistUpdateItemInWishlistRequestPayload(
                    preferred_quantity = '', 
                    description = wishlist.models.wishlist_localized_text.wishlistLocalizedText(
                        value = {
                            'key' : ''
                            }, ), 
                    customer_grn = '', ),
                payload_mask = ''
            )
        else:
            return WishlistUpdateItemInWishlistRequest(
                tenant_id = '',
                id = '',
                payload = wishlist.models.wishlist_update_item_in_wishlist_request_payload.wishlistUpdateItemInWishlistRequestPayload(
                    preferred_quantity = '', 
                    description = wishlist.models.wishlist_localized_text.wishlistLocalizedText(
                        value = {
                            'key' : ''
                            }, ), 
                    customer_grn = '', ),
                payload_mask = '',
        )
        """

    def testWishlistUpdateItemInWishlistRequest(self):
        """Test WishlistUpdateItemInWishlistRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
