# coding: utf-8

"""
    Wishlist Service

    API for managing wishlists

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from wishlist.models.wishlist_bulk_remove_items_from_wishlists_request import WishlistBulkRemoveItemsFromWishlistsRequest

class TestWishlistBulkRemoveItemsFromWishlistsRequest(unittest.TestCase):
    """WishlistBulkRemoveItemsFromWishlistsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WishlistBulkRemoveItemsFromWishlistsRequest:
        """Test WishlistBulkRemoveItemsFromWishlistsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WishlistBulkRemoveItemsFromWishlistsRequest`
        """
        model = WishlistBulkRemoveItemsFromWishlistsRequest()
        if include_optional:
            return WishlistBulkRemoveItemsFromWishlistsRequest(
                tenant_id = '',
                item_grns = [
                    ''
                    ],
                wishlist_ids = [
                    ''
                    ]
            )
        else:
            return WishlistBulkRemoveItemsFromWishlistsRequest(
                tenant_id = '',
                item_grns = [
                    ''
                    ],
        )
        """

    def testWishlistBulkRemoveItemsFromWishlistsRequest(self):
        """Test WishlistBulkRemoveItemsFromWishlistsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
