# coding: utf-8

"""
    Wishlist Service

    API for managing wishlists

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from wishlist.models.wishlist_list_wishlists_request import WishlistListWishlistsRequest

class TestWishlistListWishlistsRequest(unittest.TestCase):
    """WishlistListWishlistsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WishlistListWishlistsRequest:
        """Test WishlistListWishlistsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WishlistListWishlistsRequest`
        """
        model = WishlistListWishlistsRequest()
        if include_optional:
            return WishlistListWishlistsRequest(
                tenant_id = '',
                page_size = 56,
                page_token = '',
                filter = wishlist.models.list_wishlists_request_filter.ListWishlistsRequestFilter(
                    customer_grn = '', ),
                filter_mask = ''
            )
        else:
            return WishlistListWishlistsRequest(
                tenant_id = '',
        )
        """

    def testWishlistListWishlistsRequest(self):
        """Test WishlistListWishlistsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
