# coding: utf-8

"""
    Wishlist Service

    API for managing wishlists

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class WishlistPermission(str, Enum):
    """
    WishlistPermission
    """

    """
    allowed enum values
    """
    UNKNOWN_PERMISSION = 'UNKNOWN_PERMISSION'
    VIEW_PERMISSION = 'VIEW_PERMISSION'
    EDIT_PERMISSION = 'EDIT_PERMISSION'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WishlistPermission from a JSON string"""
        return cls(json.loads(json_str))


