# coding: utf-8

"""
    Wishlist Service

    API for managing wishlists

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel
from pydantic import Field
from wishlist.models.wishlist_are_items_in_wishlists_response_payload import WishlistAreItemsInWishlistsResponsePayload
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class WishlistAreItemsInWishlistsResponse(BaseModel):
    """
    WishlistAreItemsInWishlistsResponse
    """ # noqa: E501
    item_grn_map: Optional[Dict[str, WishlistAreItemsInWishlistsResponsePayload]] = Field(default=None, alias="itemGrnMap")
    __properties: ClassVar[List[str]] = ["itemGrnMap"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WishlistAreItemsInWishlistsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in item_grn_map (dict)
        _field_dict = {}
        if self.item_grn_map:
            for _key in self.item_grn_map:
                if self.item_grn_map[_key]:
                    _field_dict[_key] = self.item_grn_map[_key].to_dict()
            _dict['itemGrnMap'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of WishlistAreItemsInWishlistsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "itemGrnMap": dict(
                (_k, WishlistAreItemsInWishlistsResponsePayload.from_dict(_v))
                for _k, _v in obj.get("itemGrnMap").items()
            )
            if obj.get("itemGrnMap") is not None
            else None
        })
        return _obj


